### ISSUE TITLE
missing model 

### ISSUE THREAD

**Issue by madwurmz** [Gourieff/sd-webui-reactor#131]
### First, confirm

- [X] I have read the [instruction](https://github.com/Gourieff/sd-webui-reactor/blob/main/README.md) carefully
- [X] I have searched the existing issues
- [X] I have updated the extension to the latest version

### What happened?

Just installed reactor in SD A1111 'install from URL' , I got this error about a missing model, an unknown file called insightface in models folder , so nowhere to place model manually.
I see other people same complain and a message saying its fixed but I still got this error, I got windows 10, 1080ti and everything up-to-date..

### Steps to reproduce the problem

1. Go to SD
2. Press Install from URL
3. ... restart ..

### Sysinfo

windows 10, SD A1111, 1080ti

### Relevant console log

```Shell
*** Command: "D:\AI\stable-diffusion-webui\venv\Scripts\python.exe" "D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\install.py"
*** Error code: 1
*** stderr:
*** Downloading...:   0%|          | 0.00/529M [00:00<?, ?B/s]
*** Downloading...:   0%|          | 0.00/529M [00:00<?, ?B/s]
*** Traceback (most recent call last):
***   File "D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\install.py", line 69, in <module>
***     download(model_url, model_path)
***   File "D:\AI\stable-diffusion-webui\extensions\sd-webui-reactor\install.py", line 63, in download
***     urllib.request.urlretrieve(url, path, reporthook=lambda count, block_size, total_size: progress.update(block_size))
***   File "C:\Users\madwu\AppData\Local\Programs\Python\Python310\lib\urllib\request.py", line 251, in urlretrieve
***     tfp = open(filename, 'wb')
*** FileNotFoundError: [Errno 2] No such file or directory: 'D:\\AI\\stable-diffusion-webui\\models\\insightface\\inswapper_128.onnx'
```

**Comment by madwurmz** [comment]
it could be related to my visual studio 2022 install ,Im trying to install again hope for the best  🚶‍♂️

**Comment by Lesani** [comment]
Getting the same, even though my VS2022 is installed, up-to-date and working otherwise.
Which modules of VS2022 need to be installed?

**Comment by spice3d** [comment]
I think it's a bug in the install script. It's supposed to download inswapper_128.onnx and put it in the models\insightface folder. Instead it creates a file named insightface in the models folder. There are two possible solutions: 1. Rename the insightface file to inswapper_128.onnx and put it in the models\insightface folder, or; 2. Delete the insightface file, create an empty models\insightface folder, and then re-run the install. (to the dev, I think it's the model_path = os.path.join(models_dir, model_name) line.)

**Comment by Lesani** [comment]
Yes, indeed it created a file instead of a folder, but the file was also broken, I had to re-download it directly from https://github.com/facefusion/facefusion-assets/releases/download/models/inswapper_128.onnx here and put it in models\insightface then everything started working

**Comment by madwurmz** [comment]
> Getting the same, even though my VS2022 is installed, up-to-date and working otherwise. Which modules of VS2022 need to be installed?

In the visual studio installer,  I got an update and also, I already had Visual Studio Build Tools 2022, but I noticed compared to a tutorial I needed the 'Visual Studio Community 2022' too, then after 'install without any Workloads selected'    I deleted and reinstalled the extention and it works fine now.

**Comment by Gourieff** [comment]
I don't know guys who you got this error 🤷‍♂️ I've just tried to install from the scratch and everything is ok, the inswapper model file has been successfully downloaded into the `models\insightface` directory with the correct name `inswapper_128.onnx`

**Comment by Gourieff** [comment]
Ok! I got it! This error appears when install.py tries to rename the old "roop" folder
Will be fixed soon

**Comment by Gourieff** [comment]
Fixed https://github.com/Gourieff/sd-webui-reactor/commit/6a110ccaa38015fdf7dabfae537ce40b945ef545

**Comment by madwurmz** [comment]
> Ok! I got it! This error appears when install.py tries to rename the old "roop" folder Will be fixed soon

ah yes cool , nice work! indeed the first time I failed install my roop was still active I think thats what you mean

**Comment by bigsk1** [comment]
also failed, added insightface folder and moved inswapper file into that folder, restarted and is now working. This was an hour ago so the fix https://github.com/Gourieff/sd-webui-reactor/commit/6a110ccaa38015fdf7dabfae537ce40b945ef545 did not solve for me, I did have roop folder with inswapper file inside before.

**Comment by Gourieff** [comment]
> also failed, added insightface folder and moved inswapper file into that folder, restarted and is now working. This was an hour ago so the fix [6a110cc](https://github.com/Gourieff/sd-webui-reactor/commit/6a110ccaa38015fdf7dabfae537ce40b945ef545) did not solve for me, I did have roop folder with inswapper file inside before.

Did you update the extension by `git pull` or via WebUI?

**Comment by bigsk1** [comment]
> > also failed, added insightface folder and moved inswapper file into that folder, restarted and is now working. This was an hour ago so the fix [6a110cc](https://github.com/Gourieff/sd-webui-reactor/commit/6a110ccaa38015fdf7dabfae537ce40b945ef545) did not solve for me, I did have roop folder with inswapper file inside before.
> 
> Did you update the extension by `git pull` or via WebUI?

fresh install just noticed the extention from a youtube video, used oobaba webui and added the git repo.

**Comment by madwurmz** [comment]
@bigsk1  I think when you say 'and is now working. ' you meant to say 'is not working' ?

you also mention you manually moved the model into a folder, but to install again you should remove all that, remove the folder , and do 'install from url'. and also first disable that roop extension. i'm not saying I have all the answers  I'm just trying to help  🐤 

> > > also failed, added insightface folder and moved inswapper file into that folder, restarted and is now working. This was an hour ago so the fix [6a110cc](https://github.com/Gourieff/sd-webui-reactor/commit/6a110ccaa38015fdf7dabfae537ce40b945ef545) did not solve for me, I did have roop folder with inswapper file inside before.
> > 
> > 
> > Did you update the extension by `git pull` or via WebUI?
> 
> fresh install just noticed the extention from a youtube video, used auto1111 webui and added the git repo.

**Comment by bigsk1** [comment]
> @bigsk1 I think when you say 'and is now working. ' you meant to say 'is not working' ?
> 
> you also mention you manually moved the model into a folder, but to install again you should remove all that, remove the folder , and do 'install from url'. and also first disable that roop extension. i'm not saying I have all the answers I'm just trying to help 🐤
> 
> > > > also failed, added insightface folder and moved inswapper file into that folder, restarted and is now working. This was an hour ago so the fix [6a110cc](https://github.com/Gourieff/sd-webui-reactor/commit/6a110ccaa38015fdf7dabfae537ce40b945ef545) did not solve for me, I did have roop folder with inswapper file inside before.
> > > 
> > > 
> > > Did you update the extension by `git pull` or via WebUI?
> > 
> > 
> > fresh install just noticed the extention from a youtube video, used auto1111 webui and added the git repo.

no what I said is correct and now is working after

1. making a folder insightface
2. adding  inswapper file into that folder

I bring this up because the hotfix was supposed to work for this? AgaIn I found this extention today, fresh git download from auto111 web ui, and got error. The roop was disabled from the beginning so not an issue.

**Comment by madwurmz** [comment]
ah that makes sense yes! 👍  I'm also combining this with AnimateDiff , so going from faulty to smooth install,  I had disabled all other extensions , disabled xformers and updated / reinstalled Visual Studio, I dont know what but I did something right.
I could guess missing Visual Studio could potentially lead to some issues with installing a GitHub repository.

Do you also have the proper models folder inside the insightface folder with the folder called  buffalo_l containing 5 onnx files?


> > @bigsk1 I think when you say 'and is now working. ' you meant to say 'is not working' ?
> > you also mention you manually moved the model into a folder, but to install again you should remove all that, remove the folder , and do 'install from url'. and also first disable that roop extension. i'm not saying I have all the answers I'm just trying to help 🐤
> > > > > also failed, added insightface folder and moved inswapper file into that folder, restarted and is now working. This was an hour ago so the fix [6a110cc](https://github.com/Gourieff/sd-webui-reactor/commit/6a110ccaa38015fdf7dabfae537ce40b945ef545) did not solve for me, I did have roop folder with inswapper file inside before.
> > > > 
> > > > 
> > > > Did you update the extension by `git pull` or via WebUI?
> > > 
> > > 
> > > fresh install just noticed the extention from a youtube video, used auto1111 webui and added the git repo.
> 
> no what I said is correct and now is working after
> 
>     1. making a folder insightface
> 
>     2. adding  inswapper file into that folder
> 
> 
> I bring this up because the hotfix was supposed to work for this? AgaIn I found this extention today, fresh git download from auto111 web ui, and got error. The roop was disabled from the beginning so not an issue. Just a FYI. Is all working for me

**Comment by bigsk1** [comment]
yes these were downloaded automatically it seems once I started up the webui. I'm glad this project is continuing I noticed last week roop was no longer being worked on.
